before_script:
  - perl -v | grep '^This is'
  - curl -L https://cpanmin.us/ -o cpanm

test:
  script:
    - perl cpanm --installdeps .
    - perl Makefile.PL
    - make
    - RELEASE_TESTING=1 make test
