before_script:
  - perl -v | grep '^This is'

release:
  script:
    - perl Makefile.PL
    - make
    - RELEASE_TESTING=1 make test

user:
  script:
    - perl Makefile.PL
    - make
    - make test
